# Generated by Django 4.2.3 on 2024-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
